name: Performance Benchmarks

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment
        run: |
          mkdir -p data
          touch data/bot.db
          cp .env.template .env
          echo "DISCORD_TOKEN=test_token" >> .env
          echo "CLIENT_ID=123456789" >> .env

      - name: Checkout main branch pr-baseline
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          if ! git checkout origin/main -- tests/data/pr-baseline.json; then
            echo "ERROR: No baseline exists on main branch"
            echo "Please push to main branch first to establish baseline"
            exit 1
          fi
          git checkout origin/main -- tests/check-regressions.js

      - name: Run benchmarks
        run: npm run bench

      - name: Check for regressions
        run: node tests/check-regressions.js

      - name: Upload benchmark results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-results
          path: tests/data/pr-results.json

      - name: Update pr-baseline on main
        if: github.ref == 'refs/heads/main'
        run: |
          cp tests/data/pr-results.json tests/data/pr-baseline.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add tests/data/pr-baseline.json
          git commit -m "Update performance baseline [skip ci]" || echo "No changes"
          git push || echo "No push needed"